services:
  - type: web
    name: flask-tensorflow-app
    env: python
    region: oregon
    buildCommand: |
  sudo apt-get update
  sudo apt-get install -y libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
  pip install -r requirements.txt


    startCommand: flask run --host=0.0.0.0 --port=10000
    envVars:
      - key: FLASK_APP
        value: API.py
      - key: FLASK_ENV
        value: production
